version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/control_day
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/control_day

    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - postgres
    networks:
      - app-net

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: control_day
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./backend/src/db/init:/docker-entrypoint-initdb.d
    networks:
      - app-net

volumes:
  mongo-data:
  pg-data:

networks:
  app-net:
    driver: bridge
