version: '3.9'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    environment:
      PORT: 5000
      PGUSER: myuser
      PGPASSWORD: mypassword
      PGDATABASE: mydb
      PGHOST: postgres
      PGPORT: 5432
      MONGO_URI: mongodb://mongo:27017/mydb
      JWT_SECRET: supersecret
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  postgres_data:
  mongo_data:
